import Head from "next/head";
import styles from "@/styles/LoginForm.module.sass";
import { useState } from "react";
import useAuth from "@/hook/useAuth";

const LoginForm = () => {
  const [account, setAccount] = useState("");
  const [password, setPassword] = useState("");
  const { login } = useAuth();
  const onLogin = () => {
    login(account, password);
  }

  return(
    <>
      <Head>
        <title>登入頁面</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container d-flex justify-content-center align-items-center ${styles.main}`}>
        <div className={`card ${styles.w300px} ${styles.h200px}`}>
          <div className="card-header fs-3">登入</div>
          <div className="card-body">
          <input 
            type="text" 
            className="form-control mb-2" 
            placeholder="帳號"
            value={account}
            onChange={(e) => setAccount(e.target.value)}
          />
          <input 
            type="password" 
            className="form-control mb-2" 
            placeholder="密碼"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          </div>
          <div className="card-footer d-flex justify-content-end">
            <div className="btn btn-primary" onClick={onLogin}>登入</div>
          </div>
        </div>
      </main>
    </>
  )
}

export default LoginForm;