import Head from "next/head";
import Image from "next/image";
import { AuthContext } from '@/context/AuthContext';
import { useContext } from "react";
import useAuth from "@/hook/useAuth";

export default function Home() {
  const {user} = useContext(AuthContext);
  const { logout } = useAuth();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1>主要頁面</h1>
        <div className="d-flex align-items-end">
          {user && user.head && (
            <Image src={user.head} alt="User Profile" width={100} height={100} />
          )}
          <div className="btn btn-primary" onClick={logout}>登出</div>
        </div>
      </main>
    </>
  );
}
